apiVersion: v1
kind: Service
metadata:
  name: his-cdss
  namespace: his-app
  labels:
    app: his-cdss
spec:
  type: ClusterIP
  ports:
    - port: 8088
      targetPort: 8088
      protocol: TCP
  selector:
    app: his-cdss
