apiVersion: v1
kind: Service
metadata:
  name: his-platform
  namespace: his-app
  labels:
    app: his-platform
spec:
  type: ClusterIP
  ports:
    - port: 8091
      targetPort: 8091
      protocol: TCP
  selector:
    app: his-platform
