apiVersion: v1
kind: Service
metadata:
  name: his-gateway
  namespace: his-app
  labels:
    app: his-gateway
    app.kubernetes.io/name: his-gateway
    app.kubernetes.io/part-of: smart-his
spec:
  type: NodePort
  selector:
    app: his-gateway
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      nodePort: 30080
      protocol: TCP
