apiVersion: v1
kind: Namespace
metadata:
  name: his-infra
  labels:
    app.kubernetes.io/part-of: smart-his
---
apiVersion: v1
kind: Namespace
metadata:
  name: his-app
  labels:
    app.kubernetes.io/part-of: smart-his
