apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: his-infra
  labels:
    app: redis
    app.kubernetes.io/part-of: smart-his
data:
  redis.conf: |
    maxmemory 512mb
    maxmemory-policy allkeys-lru
    save ""
    appendonly no
