-- Smart HIS - Idempotent database initialization
-- Creates unified 'his' role and 11 service schemas

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'his') THEN
    CREATE ROLE his LOGIN;
  END IF;
END $$;

ALTER ROLE his WITH PASSWORD :'app_password';

GRANT CONNECT ON DATABASE his TO his;

CREATE SCHEMA IF NOT EXISTS his_auth       AUTHORIZATION his;
CREATE SCHEMA IF NOT EXISTS his_patient    AUTHORIZATION his;
CREATE SCHEMA IF NOT EXISTS his_clinical   AUTHORIZATION his;
CREATE SCHEMA IF NOT EXISTS his_resource   AUTHORIZATION his;
CREATE SCHEMA IF NOT EXISTS his_operations AUTHORIZATION his;
CREATE SCHEMA IF NOT EXISTS his_collab     AUTHORIZATION his;
CREATE SCHEMA IF NOT EXISTS his_pharma     AUTHORIZATION his;
CREATE SCHEMA IF NOT EXISTS his_cdss       AUTHORIZATION his;
CREATE SCHEMA IF NOT EXISTS his_drg        AUTHORIZATION his;
CREATE SCHEMA IF NOT EXISTS his_emergency  AUTHORIZATION his;
CREATE SCHEMA IF NOT EXISTS his_platform   AUTHORIZATION his;
