-- Legacy emergency V1 for upgrade testing
-- This represents the historical schema that existed before V2 alignment

CREATE TABLE emg_triage (
    id                BIGINT        NOT NULL,
    triage_no         VARCHAR(32)   NOT NULL,
    patient_id        BIGINT        NOT NULL,
    encounter_id      BIGINT,
    triage_level      SMALLINT      NOT NULL,
    triage_time       TIMESTAMP     NOT NULL,
    chief_complaint   VARCHAR(500),
    vital_signs       TEXT,
    triage_nurse_id   BIGINT,
    triage_nurse_name VARCHAR(64),
    target_dept_id    BIGINT,
    target_dept_name  VARCHAR(64),
    wait_time_minutes INTEGER,
    triage_status     VARCHAR(20)   NOT NULL,
    created_by        VARCHAR(64),
    created_time      TIMESTAMP,
    updated_by        VARCHAR(64),
    updated_time      TIMESTAMP,
    deleted           SMALLINT      NOT NULL DEFAULT 0,
    CONSTRAINT pk_emg_triage PRIMARY KEY (id),
    CONSTRAINT uk_emg_triage_no UNIQUE (triage_no)
);

CREATE TABLE emg_resuscitation (
    id                      BIGINT        NOT NULL,
    resuscitation_no        VARCHAR(32)   NOT NULL,
    patient_id              BIGINT        NOT NULL,
    encounter_id            BIGINT,
    triage_id               BIGINT,
    start_time              TIMESTAMP     NOT NULL,
    end_time                TIMESTAMP,
    resuscitation_type      VARCHAR(20),
    team_leader_id          BIGINT,
    team_leader_name        VARCHAR(64),
    team_members            TEXT,
    procedures              TEXT,
    medications             TEXT,
    outcome                 VARCHAR(20),
    outcome_summary         TEXT,
    resuscitation_status    VARCHAR(20)   NOT NULL,
    created_by              VARCHAR(64),
    created_time            TIMESTAMP,
    updated_by              VARCHAR(64),
    updated_time            TIMESTAMP,
    deleted                 SMALLINT      NOT NULL DEFAULT 0,
    CONSTRAINT pk_emg_resuscitation PRIMARY KEY (id),
    CONSTRAINT uk_emg_resuscitation_no UNIQUE (resuscitation_no)
);

CREATE TABLE emg_green_channel (
    id                  BIGINT        NOT NULL,
    channel_no          VARCHAR(32)   NOT NULL,
    patient_id          BIGINT        NOT NULL,
    encounter_id        BIGINT,
    triage_id           BIGINT,
    channel_type        VARCHAR(30)   NOT NULL,
    activate_time       TIMESTAMP     NOT NULL,
    activate_reason     VARCHAR(500),
    target_dept_id      BIGINT,
    target_dept_name    VARCHAR(64),
    coordinator_id      BIGINT,
    coordinator_name    VARCHAR(64),
    key_timepoints      TEXT,
    channel_status      VARCHAR(20)   NOT NULL,
    close_time          TIMESTAMP,
    close_summary       TEXT,
    created_by          VARCHAR(64),
    created_time        TIMESTAMP,
    updated_by          VARCHAR(64),
    updated_time        TIMESTAMP,
    deleted             SMALLINT      NOT NULL DEFAULT 0,
    CONSTRAINT pk_emg_green_channel PRIMARY KEY (id),
    CONSTRAINT uk_emg_green_channel_no UNIQUE (channel_no)
);

CREATE TABLE emg_observation (
    id                      BIGINT        NOT NULL,
    observation_no          VARCHAR(32)   NOT NULL,
    patient_id              BIGINT        NOT NULL,
    encounter_id            BIGINT,
    triage_id               BIGINT,
    bed_no                  VARCHAR(20),
    admit_time              TIMESTAMP     NOT NULL,
    expected_discharge_time TIMESTAMP,
    actual_discharge_time   TIMESTAMP,
    observation_diagnosis   VARCHAR(500),
    treatment_plan          TEXT,
    nurse_station           VARCHAR(64),
    doctor_id               BIGINT,
    doctor_name             VARCHAR(64),
    observation_status      VARCHAR(20)   NOT NULL,
    discharge_summary       TEXT,
    created_by              VARCHAR(64),
    created_time            TIMESTAMP,
    updated_by              VARCHAR(64),
    updated_time            TIMESTAMP,
    deleted                 SMALLINT      NOT NULL DEFAULT 0,
    CONSTRAINT pk_emg_observation PRIMARY KEY (id),
    CONSTRAINT uk_emg_observation_no UNIQUE (observation_no)
);
