apiVersion: v1
kind: Service
metadata:
  name: his-resource
  namespace: his-app
  labels:
    app: his-resource
    app.kubernetes.io/name: his-resource
    app.kubernetes.io/part-of: smart-his
spec:
  type: ClusterIP
  selector:
    app: his-resource
  ports:
    - name: http
      port: 8084
      targetPort: 8084
      protocol: TCP
