apiVersion: v1
kind: Service
metadata:
  name: his-auth
  namespace: his-app
  labels:
    app: his-auth
    app.kubernetes.io/name: his-auth
    app.kubernetes.io/part-of: smart-his
spec:
  type: ClusterIP
  selector:
    app: his-auth
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      protocol: TCP
