apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  namespace: his-infra
  labels:
    app: prometheus
    app.kubernetes.io/part-of: smart-his
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
  labels:
    app: prometheus
    app.kubernetes.io/part-of: smart-his
rules:
  - apiGroups: [""]
    resources:
      - pods
      - nodes
      - nodes/metrics
      - services
      - endpoints
    verbs: ["get", "list", "watch"]
  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus
  labels:
    app: prometheus
    app.kubernetes.io/part-of: smart-his
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus
subjects:
  - kind: ServiceAccount
    name: prometheus
    namespace: his-infra
