apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-data
  namespace: his-infra
  labels:
    app: kafka
    app.kubernetes.io/part-of: smart-his
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hostpath
  resources:
    requests:
      storage: 5Gi
